name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ["${{ matrix.os }}"]
    strategy:
      matrix:
        os:
          - macos-11
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Build & test
        run: bazelisk test //... --config=ci --config=cpu
