name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ["${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - ubuntu-18.04
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
            ~/_bazel_*
            /private/var/tmp/_bazel_*
          key: ${{ matrix.os }}

      - name: Build & test
        run: bazelisk test //... --config=ci --config=cpu
